<a href="https://colab.research.google.com/github/JCelisR/bootcamp/blob/main/PROYECTOM3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Configurar una semilla para que los resultados sean reproducibles
np.random.seed(42)

# 1. Generar 100 IDs de clientes (del 1001 al 1100)
ids_clientes = np.arange(1001, 1101)

# 2. Generar 100 montos de transacciones
# Usamos una distribución normal para simular compras reales (media de 500, desvío de 150)
montos = np.random.normal(500, 150, 100).round(2)

# 3. Simular cantidad de productos por transacción (entre 1 y 10)
cantidades = np.random.randint(1, 11, size=100)

# Unimos todo en una matriz (opcional, para ver la estructura)
dataset_inicial = np.column_stack((ids_clientes, montos, cantidades))
print("Primeras 5 filas (ID, Monto, Cantidad):")
print(dataset_inicial[:5])


Primeras 5 filas (ID, Monto, Cantidad):
[[1.0010e+03 5.7451e+02 9.0000e+00]
 [1.0020e+03 4.7926e+02 5.0000e+00]
 [1.0030e+03 5.9715e+02 1.0000e+00]
 [1.0040e+03 7.2845e+02 3.0000e+00]
 [1.0050e+03 4.6488e+02 1.0000e+01]]
